name: CI for all services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [admin-ui, admin-backend, customer-ui, customer-backend]

    steps:
      # -----------------------------
      # Checkout Code
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # -----------------------------
      # SonarQube Scan (per service)
      # -----------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ${{ matrix.service }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      

#      - name: Install dependencies
#        if: contains(matrix.service, 'backend')
#        run: |
#          pip install -r ${{ matrix.service }}/requirements.txt
#          pip install flake8 bandit pytest

#      - name: Lint check
#        if: contains(matrix.service, 'backend')
#        run: flake8 ${{ matrix.service }}

#      - name: Security scan
#        if: contains(matrix.service, 'backend')
#        run: bandit -r ${{ matrix.service }}

#      - name: Run tests
#        if: contains(matrix.service, 'backend')
#        run: pytest ${{ matrix.service }}

      # -----------------------------
      # Build Docker Image (per service)
      # -----------------------------
      - name: Build Docker Image
        run: |
          docker build \
            -f ${{ matrix.service }}/Dockerfile \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} \
            ${{ matrix.service }}

      # -----------------------------
      # Trivy Image Scan
      # -----------------------------
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      # -----------------------------
      # Login to Docker Hub
      # -----------------------------
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # -----------------------------
      # Push Image
      # -----------------------------
#      - name: Push Docker Image
#        run: |
#          docker push $DOCKERHUB_USERNAME/${{ matrix.service }}:${{ github.sha }}
